name: Pull Request Title Lint
runs:
  using: node20
  main: dist/main.js
inputs:
  title:
    required: true
  summary:
    required: false
    default: false
  into:
    required: true
outputs:
  increment:
    description: The semver increment type
  hard:
    description: Whether to bypass v0 limitations
